version: 2

jobs:
  build:
    docker:
      - image: node:8-alpine
    working_directory: ~/repo/WebService
    branches:
      only:
        - master
    steps:
      - checkout
          path: ~/repo
      - restore_cache:
          keys:
            - yarn-v1-{{ checksum "yarn.lock" }}
            - yarn-v1-
      - run:
          name: Install NPM modules
          command: |
            yarn install
            yarn add firebase-tools --dev
      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn/v1
      - run:
          name: Build
          command: |
            yarn relay
            yarn build
      # - run:
      #     name: Test
      #     command: |
      #       yarn lint
      #       yarn test --forceExit
      # - run:
      #     name: Deploy
      #     command: |
      #       if [ "${CIRCLE_BRANCH}" == "master" ]; then
      #         ./node_modules/firebase-tools/bin/firebase use dev
      #         ./node_modules/firebase-tools/bin/firebase deploy --token=$FIREBASE_TOKEN
      #       fi
